CREATE TABLE IF NOT EXISTS DELIVERY_COURIER_USER
(
    DELIVERY_COURIER_USER_ID UUID         NOT NULL PRIMARY KEY,
    NAME                     VARCHAR(255) NOT NULL,
    REGISTER_NUMBER          VARCHAR(11)  NOT NULL,
    BIRTHDAY_DATE            DATE         NOT NULL,
    ACTIVE                   BOOLEAN      NOT NULL,
    ONLINE                   BOOLEAN      NOT NULL,
    CREATED_AT               timestamptz  NOT NULL,
    UPDATED_AT               timestamptz  NOT NULL
);

CREATE TABLE IF NOT EXISTS DELIVERY_ADDRESS
(
    ADDRESS_ID UUID         NOT NULL PRIMARY KEY,
    STREET     VARCHAR(255) NOT NULL,
    CITY       VARCHAR(255) NOT NULL,
    ZIP_CODE   VARCHAR(50)  NOT NULL,
    COUNTRY    VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS DELIVERY
(
    DELIVERY_ID              UUID NOT NULL PRIMARY KEY,
    DELIVERY_COURIER_USER_ID UUID NOT NULL,
    USER_ID                  UUID NOT NULL,
    ORDER_ID                 UUID NOT NULL,
    ADDRESS_SOURCE_ID        UUID NOT NULL,
    ADDRESS_DESTINATION_ID   UUID NOT NULL,
    DELIVERY_AT              timestamptz,
    CONSTRAINT FK_DELIVERY_DELIVERY_COURIER_USER_ID FOREIGN KEY (DELIVERY_COURIER_USER_ID) REFERENCES DELIVERY_COURIER_USER (DELIVERY_COURIER_USER_ID),
    CONSTRAINT FK_DELIVERY_ADDRESS_SOURCE_ID FOREIGN KEY (ADDRESS_SOURCE_ID) REFERENCES DELIVERY_ADDRESS (ADDRESS_ID),
    CONSTRAINT FK_DELIVERY_ADDRESS_DESTINATION_ID FOREIGN KEY (ADDRESS_DESTINATION_ID) REFERENCES DELIVERY_ADDRESS (ADDRESS_ID)
);