CREATE TABLE IF NOT EXISTS ORDER_ADDRESS
(
    ORDER_ADDRESS_ID UUID PRIMARY KEY NOT NULL,
    STREET           VARCHAR(255)     NOT NULL,
    CITY             VARCHAR(255)     NOT NULL,
    ZIP_CODE         VARCHAR(50)      NOT NULL,
    COUNTRY          VARCHAR(50)      NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_RESTAURANT
(
    ORDER_RESTAURANT_ID         UUID         NOT NULL PRIMARY KEY,
    RESTAURANT_ID               UUID         NOT NULL,
    NAME                        VARCHAR(255) NOT NULL,
    COMPANY_REGISTRATION_NUMBER VARCHAR(14)
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ORDER_ID                 UUID           NOT NULL PRIMARY KEY,
    RESTAURANT_ID            UUID           NOT NULL,
    ADDRESS_SOURCE_ID        UUID           NOT NULL,
    ADDRESS_DESTINATION_ID   UUID           NOT NULL,
    USER_ID                  UUID           NOT NULL,
    STATUS                   VARCHAR(100)   NOT NULL,
    VERSION                  BIGINT         NOT NULL,
    CREATED_AT               timestamptz    NOT NULL,
    UPDATED_AT               timestamptz    NOT NULL,
    PREPARATION_INSTRUCTIONS VARCHAR(1000)  NOT NULL,
    PAYMENT_METHOD           VARCHAR(255)   NOT NULL,
    TOTAL                    DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_ORDERS_ADDRESS_SOURCE_ID FOREIGN KEY (ADDRESS_SOURCE_ID) REFERENCES ORDER_ADDRESS (ORDER_ADDRESS_ID),
    CONSTRAINT FK_ORDERS_ADDRESS_DESTINATION_ID FOREIGN KEY (ADDRESS_DESTINATION_ID) REFERENCES ORDER_ADDRESS (ORDER_ADDRESS_ID),
    CONSTRAINT FK_ORDERS_RESTAURANT_ID FOREIGN KEY (RESTAURANT_ID) REFERENCES ORDER_RESTAURANT (ORDER_RESTAURANT_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(
    ORDER_ITEM_ID UUID PRIMARY KEY NOT NULL,
    ORDER_ID      UUID             NOT NULL,
    NAME          VARCHAR(255)     NOT NULL,
    DESCRIPTION   VARCHAR(500),
    PRICE         DECIMAL(10, 2)   NOT NULL,
    QUANTITY      INT DEFAULT 1    NOT NULL,
    CONSTRAINT FK_ORDER_ITEMS_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);