CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS TICKET
(
    TICKET_ID                UUID           NOT NULL PRIMARY KEY,
    ORDER_ID                 UUID           NOT NULL,
    RESTAURANT_ID            UUID           NOT NULL,
    STATUS                   VARCHAR(100)   NOT NULL,
    TOTAL                    DECIMAL(10, 2) NOT NULL,
    PREPARATION_INSTRUCTIONS VARCHAR(255)   NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ITEM_ID     UUID           NOT NULL PRIMARY KEY,
    ORDER_ID    UUID           NOT NULL,
    NAME        VARCHAR(255)   NOT NULL,
    DESCRIPTION VARCHAR(500),
    PRICE       DECIMAL(10, 2) NOT NULL,
    QUANTITY    INT DEFAULT 1  NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
    ADDRESS_ID UUID PRIMARY KEY NOT NULL,
    STREET     VARCHAR(255)     NOT NULL,
    CITY       VARCHAR(255)     NOT NULL,
    ZIP_CODE   VARCHAR(50)      NOT NULL,
    COUNTRY    VARCHAR(50)      NOT NULL
);

CREATE TABLE IF NOT EXISTS RESTAURANT
(
    RESTAURANT_ID         UUID         NOT NULL PRIMARY KEY,
    ADDRESS_ID UUID         NOT NULL,
    NAME                  VARCHAR(255) NOT NULL,
    REGISTER              VARCHAR(14)  NOT NULL,
    OPEN_AT               varchar(5)   NOT NULL,
    CLOSE_AT              varchar(5)   NOT NULL,
    OPEN                  BOOLEAN      NOT NULL,
    CONSTRAINT RESTAURANT_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID)
);